### ISSUE TITLE
Error invalid url

### ISSUE THREAD

**Issue by pedersla** [Necriso/ScriptableWidgets#2]
Warum genau sagt er mir hier, dass meine url invalid ist?
![15EDD658-69A5-42A5-A2BE-E25BA6264651](https://user-images.githubusercontent.com/73159687/99914495-0d37ad00-2cfe-11eb-92ec-16f648d7c648.png)

**Comment by Necriso** [comment]
Da ist ein Leerzeichen im API-Key zwischen dem letzten Zeichen (0) und dem Pipe ( | )
