### ISSUE TITLE
Error on line 78:20: TypeError: undefined is not an object (evaluating 'data.stations.length')

### ISSUE THREAD

**Issue by Goldsucher** [Necriso/ScriptableWidgets#3]
Bekomme die oben genannte Fehlermeldung. Ne Idee woran das liegen könnte?
Danke!

**Comment by Necriso** [comment]
Das liegt meist dran, dass der Radius zu niedrig eingestellt ist.
Wie sieht denn deine Konfiguration bei den Widget Parametern aus? (Bitte Api Key, falls du es hier postest weglassen).

**Comment by Goldsucher** [comment]
Okay danke, aber das hat leider nix gebracht. Ich hab einfach mal 3, 5 und 7 ausprobiert, also z.b.

api-key|3|0 oder aus dein Beispiel:
api-key|3|1|54.322|10.1355

manchmal kommt jetzt aber auch der Fehler:
Error on line 61:22: TypeError: undefined is not an object (evaluating 'value.toString')

**Comment by Necriso** [comment]
Also ich kriege mit deinen Koordinaten eine Oil! Tankstelle in der Brunswiker Straße angezeigt.
Hast du der Scriptable App den Zugriff auf das GPS erlaubt?
Das könnte noch das einzige sein woran es scheitert.

**Comment by Goldsucher** [comment]
Okay seltsam. Ich hatte das Script über ScriptDude installiert und deswegen ging es anscheinend nicht. Ich hab mir den Code jetzt nochmal manuell von Github rauskopiert und jetzt geht es.

Ich hab noch ganz kurz ne Verständnisfrage:
Zeit mir tankstellenpreise.js denn die günstige Tankstelle an?
und wenn nein:
Kann ich bei guenstigsteTankstelle.js die Location auch ohne Ortungsdienste setzen?

Vielen Dank!

**Comment by Necriso** [comment]
Komisch.
Über Scriptdude habe ich das Widget auch bei mir laufen, aber kann keine Fehler feststellen.
Tankstellenpreise zeigt nur die nächste Tankstelle oder eine feste Tankstelle an.
Die meisten benutzen das Widget um die Preise ihrer Stammtankstelle sehen zu können.

Günstigste Tankstelle hat keine Möglichkeit der fixen Hinterlegung der Koordination.
Die ist eigentlich dafür gedacht, dass wenn man unterwegs ist, sich im Umkreis von x km die günstigste Tankstelle ausgeben zu lassen.

**Comment by Goldsucher** [comment]
ah okay schade. Aber trotzdem danke für die Hilfe!
